spring.application.name=bsbblog
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/bsbblogdb}
jwt.secret=${JWT_SECRET:defaultLocalOnlySecretChangeThis}
jwt.secret=bsbBlogSuperSecretKeyForJWTSigning2026ChangeThisInProduction
